language: node_js
node_js:
  - 10
before_install:
  - npm install -g npm
script:
  - npm install
  - npm test
deploy:
  provider: heroku
  api_key: 8aae9e63-f938-4bf8-8231-052c40220328
  app: hello-node-bryon
  on:
    repo: bbarber1973/hello-node-bryon
    branch: master
